twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - 'bootstrap_5_horizontal_layout.html.twig'
when@test:
    twig:
        strict_variables: true
